package dev.rnett.kcp.development.testing.preprocessors

import org.jetbrains.kotlin.test.model.TestFile
import org.jetbrains.kotlin.test.services.ReversibleSourceFilePreprocessor
import org.jetbrains.kotlin.test.services.TestServices
import org.jetbrains.kotlin.test.services.isKtFile

class BoOpBoxPreprocessor(testServices: TestServices) : ReversibleSourceFilePreprocessor(testServices) {

    val boxFun = "\nfun box() = \"OK\" // generated by BoOpBoxPreprocessor\n"

    override fun revert(file: TestFile, actualContent: String): String {
        if (!file.isKtFile) return actualContent
        return actualContent.replace(boxFun, "")
    }

    override fun process(file: TestFile, content: String): String {
        if (!file.isKtFile) return content

        if ("fun box(" in content)
            return content

        return content + boxFun
    }
}