package auto.test.box // generated by PackagePreprocessor

@OptIn(kotlin.ExperimentalStdlibApi::class, kotlin.time.ExperimentalTime::class) // generated by BoxOptInPreprocessor
fun box() = "OK"


val a by lazy { 2 as String }