

package dev.rnett.kcp.development.testing.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerator}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/test/dump")
@TestDataPath("$PROJECT_ROOT")
public class AutoTestDumpTestGenerated extends AbstractDumpTest {
  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/test/dump"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("Dump.kt")
  public void testDump() {
    runTest("src/testData/auto/test/dump/Dump.kt");
  }
}
