

package dev.rnett.kcp.development.testing.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerator}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/test/fir")
@TestDataPath("$PROJECT_ROOT")
public class TestFirTestGenerated extends AbstractDumpingFirDiagnosticsTest {
  @Test
  public void testAllFilesPresentInFir() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/test/fir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Fir.kt")
  public void testFir() {
    runTest("src/testData/test/fir/Fir.kt");
  }
}
