

package dev.rnett.kcp.tests.auto.test.diagnostics;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.kcp.tests.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledFirTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/test/diagnostics")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
public class DiagnosticsTestGenerated extends AbstractLeveledFirTest {
  @Override
  public void configure(TestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/test/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Duplicates.kt")
  public void testDuplicates() {
    runTest("src/testData/auto/test/diagnostics/Duplicates.kt");
  }
}
