

package dev.rnett.kcp.tests.auto.test.compile;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.kcp.tests.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.NonGroupingPhaseTestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledIrTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/test/compile")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.FIR)
@TestWithLevel(level = TestLevel.IR)
public class TestCompileTestGenerated extends AbstractLeveledIrTest {
  @Override
  public void configure(NonGroupingPhaseTestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  private void run(String fileName) {
    runTest("src/testData/auto/test/compile/" + fileName);
  }

  @Test
  public void testAllFilesPresentInCompile() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/test/compile"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Dump.kt")
  public void testDump() {
    run("Dump.kt");
  }
}
