

package dev.rnett.kcp.development.test.auto.test.box;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.kcp.development.testing.generation.AutoGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import org.jetbrains.kotlin.test.TargetBackend;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledBoxTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerator}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/test/box")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.Fir)
@TestWithLevel(level = TestLevel.Ir)
@TestWithLevel(level = TestLevel.Run)
public class BoxTestGenerated extends AbstractLeveledBoxTest {
  @Override
  public void configure(TestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, AutoGenerator.class);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/test/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("Box.kt")
  public void testBox() {
    runTest("src/testData/auto/test/box/Box.kt");
  }
}
